// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "AXIS",
    defaultLocalization: "en",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "AXIS",
            targets: ["AppModule"],
            bundleIdentifier: "com.axis",
            teamIdentifier: "CFD6U2W8D6",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("__PlaceholderAppIcon"),
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            additionalInfoPlistContentFilePath: "AppInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            sources: ["AppModel", "Utilities", "Views", "AXISApp.swift"],
            resources: [
                .process("Assets.xcassets")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)